# Generated by Django 3.2.6 on 2022-03-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
